name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Setup Theos
        uses: Randomblock1/theos-action@v1

      - name: Build DEBs
        run: |
          rm -f packages/*
          gmake package FINALPACKAGE=1
          gmake package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Attach Deb To Release
        run: |
          set -x
          TAG="${GITHUB_REF##*/}-${GITHUB_SHA:0:7}"
          gh release create "$TAG" --draft --title "Draft Release"
          gh release upload "$TAG" packages/*.deb